name: febelinkWEB CI/CD

on:
  push:
    branches: [development]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Build Angular app (producción)
        run: npm run build --configuration=production

      - name: Build y despliegue local
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "82.223.118.251"
          username: "root"
          password: "o4@l4ZBIZzrmpz"
          script: |
            cd /var/www/vhosts/febelink.com/test.febelink.com/febelink
            git pull test development

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20

            npm install
            npm run build --configuration=production

            # Aquí se hace el 'cp' directo sin transferencias
            cp -r dist/browser/* /var/www/vhosts/febelink.com/test.febelink.com/
