name: febelinkWEB CI/CD

on:
  push:
    branches: [development]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Build Angular app (producción)
        run: npm run build --configuration=production

      - name: Copiar archivos al servidor remoto
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "82.223.118.251"
          username: "root"
          password: "o4@l4ZBIZzrmpz"
          source: "dist/browser/*"
          target: "/var/www/vhosts/febelink.com/test.febelink.com"
